/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.uepb.gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import my.uepb.source.AddUser;

/**
 *
 * @author Super i3
 */
public class RemoverUser extends javax.swing.JFrame {

    AddUser user = new AddUser();
    private Map<String, String> userData;
    /**
     * Creates new form RemoverUser
     */
    public RemoverUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        textPesquisa = new javax.swing.JTextField();
        panelFoto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelDados = new javax.swing.JPanel();
        textNome = new javax.swing.JLabel();
        textCargo = new javax.swing.JLabel();
        textMatricula = new javax.swing.JLabel();
        textSexo = new javax.swing.JLabel();
        panelSair = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 116, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        textPesquisa.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        textPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        textPesquisa.setText("Pesquisar matricula");
        textPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPesquisaFocusLost(evt);
            }
        });
        textPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textPesquisaMouseClicked(evt);
            }
        });
        textPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPesquisaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesquisaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 0, 32);
        jPanel1.add(textPesquisa, gridBagConstraints);

        panelFoto.setBackground(new java.awt.Color(255, 255, 255));
        panelFoto.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/uepb/imgs/removeUser.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFoto.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 11, 0);
        jPanel1.add(panelFoto, gridBagConstraints);

        panelDados.setBackground(new java.awt.Color(204, 204, 204));

        textNome.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N

        textCargo.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N

        textMatricula.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N

        textSexo.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(textSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 11, 0);
        jPanel1.add(panelDados, gridBagConstraints);

        panelSair.setBackground(new java.awt.Color(0, 0, 0));
        panelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSairMouseExited(evt);
            }
        });
        panelSair.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSair.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(panelSair, gridBagConstraints);

        btnRemover.setBackground(new java.awt.Color(255, 255, 255));
        btnRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverMouseClicked(evt);
            }
        });
        btnRemover.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/uepb/imgs/menu/subMenus/deleteUser.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        btnRemover.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jLabel5.setText("Remover usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        btnRemover.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(btnRemover, gridBagConstraints);

        btnPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisaMouseClicked(evt);
            }
        });
        btnPesquisa.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/uepb/imgs/pesquisa.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        btnPesquisa.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(btnPesquisa, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPesquisaFocusGained
        textPesquisa.setCaretPosition(0);
        
    }//GEN-LAST:event_textPesquisaFocusGained

    private void textPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesquisaKeyPressed
        String nome = textPesquisa.getText();
        if(nome.equals("Pesquisar matricula")){
            textPesquisa.setText("");
            textPesquisa.setForeground(Color.BLACK);
        }
        String pesquisa = textPesquisa.getText();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            try {
                mudarTextos(user.pesquisarUser(pesquisa));
            } catch (SQLException ex) {
                Logger.getLogger(RemoverUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_textPesquisaKeyPressed

    private void textPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesquisaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();        
        }
        
        String text = textPesquisa.getText();

        if(text.length() == 9){
            evt.consume();
        }
        
       
        
        
    }//GEN-LAST:event_textPesquisaKeyTyped

    private void textPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPesquisaFocusLost
        String idade = textPesquisa.getText();
        if(idade.equals("")){
            textPesquisa.setText("Pesquisar matricula");
            textPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        }  
    }//GEN-LAST:event_textPesquisaFocusLost

    private void textPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPesquisaMouseClicked
        String idade = textPesquisa.getText();
        if(idade.equals("Pesquisar matricula")){
            textPesquisa.setCaretPosition(0);
        } 
    }//GEN-LAST:event_textPesquisaMouseClicked

    private void btnPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaMouseClicked
        String pesquisa = textPesquisa.getText();
        try {
        mudarTextos(user.pesquisarUser(pesquisa));
        } catch (SQLException ex) {
        Logger.getLogger(RemoverUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPesquisaMouseClicked

    private void btnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseClicked
        String matricula = null;
        try{
                matricula = userData.get("matricula");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Você não selecionou nenhum usuário!");
        }
        
        if(matricula == null){
    
        } else {
            try {
                user.deletarUser(matricula);
                dispose();
                Usuarios main = new Usuarios();
                main.setVisible(true);
                
            } catch (SQLException ex) {
                Logger.getLogger(RemoverUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            //dispose();
  
    }//GEN-LAST:event_btnRemoverMouseClicked

    private void panelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseClicked
        try {
            Usuarios main = new Usuarios();
            main.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(RemoverUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_panelSairMouseClicked

    private void panelSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseEntered
        panelSair.setBackground(new Color(230,230,230));
        jLabel1.setForeground(new Color(0, 0, 0));
        panelSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelSairMouseEntered

    private void panelSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSairMouseExited
        jLabel1.setForeground(new Color(255, 255, 255));
        panelSair.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_panelSairMouseExited

    public void mudarTextos(Map userMapa){
        userData = userMapa;
        textNome.setText(userData.get("nome"));
        textMatricula.setText(userData.get("matricula"));
        textSexo.setText(userData.get("sexo"));
        
        String cargo = "";
        
        if(userData.get("cargo") == null){
            
        } else {
            if(userData.get("cargo").equals("1")){
                cargo = "Aluno";
            }
            if(userData.get("cargo").equals("2")){
                cargo = "Professor";
            }

            if(userData.get("cargo").equals("3")){
                cargo = "Coordenador";
            }
            textCargo.setText(cargo);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPesquisa;
    private javax.swing.JPanel btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelFoto;
    private javax.swing.JPanel panelSair;
    private javax.swing.JLabel textCargo;
    private javax.swing.JLabel textMatricula;
    private javax.swing.JLabel textNome;
    private javax.swing.JTextField textPesquisa;
    private javax.swing.JLabel textSexo;
    // End of variables declaration//GEN-END:variables
}
